#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/e6e9893f-894d-4491-afe7-790e8bb201ba 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float mid;
  int _moisture;
  int temp;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"


int sensor_analog;
const int sensor_pin = A0;  /* Soil moisture sensor O/P pin */
const int sensor_power_pin = 35;

void setup() {
  
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  // ----------------------------------------

  pinMode(sensor_power_pin,OUTPUT);
    
}



void loop() {
  ArduinoCloud.update();
  // Your code here 

  // Turns ON sensor
  digitalWrite(sensor_power_pin,HIGH);
  delay(2000);
  
   sensor_analog = analogRead(sensor_pin);
  _moisture = ( 100 - ( (sensor_analog/4095.00) * 100 ) );
  Serial.print("Moisture = ");
  Serial.print(_moisture);  /* Print Temperature on the serial window */
  Serial.println("%");
  
  delay(2000);              /* Wait for 1000mS */
  
  digitalWrite(sensor_power_pin,HIGH);

  delay(1000*60*2);

  
}





